# Travis CI + HTML Tidy 5.2 for Web Audio API.

language: cpp
sudo: false
addons:
  apt:
    packages:
      - tidy-html5
#install:
#  - make install_tidy
script:
#  - make check
#  - tidy -quiet -config tidyconf.txt index.html | sed -f fixup.sed | diff -U8 index.html -
  - tidy --version
  - tidy-html5 --version
branches:
  only:
    - gh-pages
