language: cpp
sudo: false
addons:
  apt:
    packages:
      - cmake
script:
  # Run html tidy but ignore any failures
  - make check || true
branches:
  only:
    - gh-pages
cache:
  directories:
    - $TRAVIS_BUILD_DIR/.support/
