language: cpp
sudo: false
install:
  - wget http://binaries.html-tidy.org/binaries/tidy-5.2.0/tidy-5.2.0-64bit.rpm
  - rpm -i tidy-5.2.0-64bit.rpm
script:
  - tidy -quiet -config tidyconf.txt index.html | sed -f fixup.sed | diff -U8 index.html -
branches:
  only:
    - gh-pages
