# Travis CI + HTML Tidy 5.2 for Web Audio API.

language: cpp
sudo: false
addons:
  apt:
    packages:
      - tidy-html5
#install:
#  - make install_tidy
script:
  - make check
branches:
  only:
    - gh-pages
