language: cpp
sudo: true
addons:
  packages:
    # For bikeshed
    - python2.7.9
    - python-dev
    - python-pip
    - python-wheel
    - libxslt1-dev
    - libxml2-dev

script:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#install-linux
  - sudo pip install pygments
  - sudo pip install lxml
  - git clone https://github.com/tabatkins/bikeshed.git

branches:
  only:
    - gh-pages

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.pip